// Auto-generated Surah vocabulary data
// Generated on: 2023-05-08T12:00:00.000Z

export const surahVocabularyData = [
  // This is a placeholder for the actual generated data
  // The real data would be generated by the SurahVocabularyGenerator
  {
    surahNumber: 1,
    surahName: "Al-Fatihah",
    words: [
      // Words would be populated here
    ],
  },
  // More Surahs would be listed here
]
